# Generated by Django 6.0.3 on 2026-04-06 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partner request', 'verbose_name_plural': 'Partner requests'},
        ),
        migrations.RemoveField(
            model_name='partnerrequest',
            name='created_store',
        ),
        migrations.RemoveField(
            model_name='partnerrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use only.', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Whether admin has handled this request.'),
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the request was marked as handled.', null=True),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='address',
            field=models.CharField(blank=True, help_text='Optional store address.', max_length=500),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='email',
            field=models.EmailField(db_index=True, help_text='Primary contact email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional free-text message.', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the contact person.', max_length=200),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='store_name',
            field=models.CharField(blank=True, help_text='Name of the interested store or retailer.', max_length=200),
        ),
    ]
