# Generated by Django 5.2.12 on 2026-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
