# Generated by Django 6.0.3 on 2026-04-08 10:56

import accounts.domain.roles
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_store_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[(accounts.domain.roles.StaffAccessLevel['RESTRICTED'], 'Restricted'), (accounts.domain.roles.StaffAccessLevel['FULL'], 'Full')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff account',
                'verbose_name_plural': 'Staff accounts',
                'ordering': ['user__username'],
            },
        ),
    ]
