# Generated by Django 6.0.3 on 2026-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='is_orderable',
            field=models.BooleanField(default=True, help_text='Whether stores may currently order the product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether the product is shown in the catalog UI.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(blank=True, help_text='Optional packaging metadata: number of sellable units in one box.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Optional product weight metadata in grams.', null=True),
        ),
    ]
