# Generated by Django 5.2.12 on 2026-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_description_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units per box', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Weight per unit in grams', null=True),
        ),
    ]
