# Generated by Django 6.0.3 on 2026-04-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='boxes',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_units_per_box',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
