# Generated by Django 6.0.8 on 2026-09-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('carts', '0001_initial'),
        ('customers', '0003_customer_activated_at_customer_activated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCart',
            fields=[
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_context', serialize=False, to='carts.cart')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business_cart', to='customers.customer')),
            ],
        ),
    ]
