# Generated by Django 6.0.8 on 2026-09-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businesscart'),
        ('orders', '0012_alter_orderline_commercial_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessOfferSelection',
        ),
    ]
