# Generated by Django 6.0.8 on 2026-09-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_remove_retailcartline_unique_retail_commercial_price_per_cart_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retailcartline',
            name='retail_cart_line_quantity_positive',
        ),
        migrations.RemoveConstraint(
            model_name='retailcartline',
            name='unique_retail_commercial_price_per_cart',
        ),
        migrations.RemoveField(
            model_name='retailcartline',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='retailcartline',
            name='commercial_price',
        ),
        migrations.DeleteModel(
            name='RetailCart',
        ),
        migrations.DeleteModel(
            name='RetailCartLine',
        ),
    ]
