# Generated by Django 6.0.8 on 2026-09-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0011_remove_retailcartline_retail_cart_line_quantity_positive_and_more'),
        ('orders', '0012_alter_orderline_commercial_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetailOfferSelection',
        ),
    ]
