# Generated by Django 6.0.8 on 2026-09-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderline_commercial_offer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_business_draft_order_per_customer',
        ),
    ]
